#ANIMATION 

FPS = 10
FRAME_INTERVAL = 1000/FPS #ms
TOTAL_FRAMES = 600 + 1

#FLOW CONSTANTS

MAX_ALLOWABLE_LIMIT_ON_EACH_LANE = 50 #vehicles
TOLERATABLE_WAIT_TIME = 30 #seconds
THRESHOLD_DENSITY_FOR_CLEARANCE = 0.3
RELEASE_RATE = 0.008